console.log('Primeira Linha \n Segunda linha')
console.log('O meu nome é "Gustavo"')
console.log("O nome dela é 'Ilze'")
console.log(`A multiplicação de 5 por 3 é ${5 * 3}`)
console.log('O' + ' meu' + ' nome' + ' é' + ' Gustavo.')